### ISSUE TITLE
(tlg1413.tlg001.1st1K-eng1) new edition metadata

### ISSUE THREAD

**Issue by charhoughton** [PerseusDL/catalog_pending#126]
@AlisonBabeu @lcerrato I'm attaching text and metadata files for the Heraclitus translation. Let me know about any edits, and thanks for your help with this.
[tlg1413.tlg001.zip](https://github.com/PerseusDL/catalog_pending/files/7576971/tlg1413.tlg001.zip)

**Comment by lcerrato** [comment]
@charhoughton 
I'll move this over but new texts get dropped into the appropriate text repo as with the volunteer work (https://github.com/OpenGreekAndLatin/First1KGreek) and new metadata requests get added here (see others that are open). Sorry about the confusion.
No texts go here as this is only for cataloging research/data.

So the texts should always be dropped in an issue, then once a text is complete, I make a request for new metadata here as one of the last steps.

As this is in process we should work on the new edition first and not go into catalog_pending until the end. 

Any general questions about what the metadata should be can go here. (We just cut and paste the metadata rather than attach the files as that is easier for Alison to quickly read.)

**Comment by lcerrato** [comment]
@charhoughton @AlisonBabeu 
I should add that this is one reason I don't want collaborators emailing us files. It's not really scalable and leads us to a more challenging workflow.

**Comment by lcerrato** [comment]
```
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:greekLit:tlg1413" xml:lang="eng" urn="urn:cts:greekLit:tlg1413.tlg001">
    <ti:title xml:lang="eng">On Unbelievable Stories</ti:title>
    <ti:translation urn="urn:cts:greekLit:tlg1413.tlg001.1st1K-eng1" workUrn="urn:cts:greekLit:tlg1413.tlg001" xml:lang="eng">
        <ti:label xml:lang="eng">On Unbelievable Stories</ti:label>
        <ti:description xml:lang="mul">Heraclitus Paradoxographus. On Unbelievable Stories. Hawes, Greta, et al.,  translators.
            Washington, DC: Center for Hellenic Studies, 2021. (digital publication).</ti:description>
    </ti:translation>
</ti:work>
```

**Comment by lcerrato** [comment]
NB I will change to "lat" for the group name.
```
<ti:textgroup xmlns:ti="http://chs.harvard.edu/xmlns/cts" urn="urn:cts:greekLit:tlg1413">
    <ti:groupname xml:lang="eng">Heraclitus Paradoxographus</ti:groupname>
</ti:textgroup>
```

**Comment by lcerrato** [comment]
see https://github.com/OpenGreekAndLatin/First1KGreek/issues/2562

**Comment by charhoughton** [comment]
@lcerrato thank you! Sorry for the confusion

**Comment by AlisonBabeu** [comment]
I've created metadata for this work so I'm closing this issue.
