### ISSUE TITLE
Anonymus.GeographiGraeciMinores.Vol1.AnonymiMensuraTotius.mods.xml

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_pending#13]
This is a subsection of Muller's _Geographi graeci minores_ Shouldn't there be a single record for _Geographi graeci minores_ with constituents for each of these parts?

Also, it looks like there are TEI encodings of _Geographi graeci minores_, or at least parts of it (e.g., https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/ggm0001/ggm001/ggm0001.ggm001.1st1K-grc1.xml) I want to make sure I understand how these things fit together.

**Comment by cwulfman** [comment]
Here's a partial MODS encoding of the Muller. There are constituents I can't resolve -- help?

[Geographi-temp.mods.xml.zip](https://github.com/PerseusDL/catalog_pending/files/1580976/Geographi-temp.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
There was originally an entire record for both individual volumes Muller's GGM, most of which was ingested into the first Perseus Catalog data creation.  The record that you found was for one of those constituent works that had no TLG ID so I had an orphan record that lived in catalog_pending for years since it couldn't be ingested in any update without an ID that could be CTS URNized.

A few years later along comes Chiara, classicist extraordinaire, with two entirely encoded volumes of the GGM, and she needed an ID and a MODS record for this work in question.  (Check out https://github.com/PerseusDL/catalog_data/issues/100) for the relevant discussion, so I created an ID this time around using the invented textgroup GGM to create a CTS-URN.

There are a number of records in catalog_pending now that I think about it that are exactly like this and may cause further confusion.

**Comment by cwulfman** [comment]
Just a placeholder: this record is in catalog_data/mods/greekLit/ggm0001/ggm001/first1K-grc1, on the pending_review branch.

**Comment by AlisonBabeu** [comment]
A catalog record was created for this long ago so I'm closing this issue.
