### ISSUE TITLE
Where do CITEURNs for authors come from?

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_pending#14]
@AlisonBabeu , looking at the MADS records in catalog_pending, I see that they do not have <identifer type='citeurn'> elements. Presumably part of the move from catalog_pending to catalog_data entails assigning citeurns. How has that been done?

**Comment by AlisonBabeu** [comment]
HI @cwulfman, yes, the addition of CITE URNs has always been done automagically I have assumed because I never created them by hand.  From looking at the catalog update document (https://docs.google.com/document/d/1Oxwg7i0xoo-ym_LfBC3UpsODoCt7z8lQiMlk7szHBiU/edit), it appears that the following happens:

-MADS importer
-parses the catalog_pending MADS xml to pull out important parts, any ids, the author name, etc.
-searches the CITE tables for authors that match the information
-if a row for the author already exists in the authors CITE:
-attempt to make sure the canonical_id is correct, add any new alternate ids, check the name and related_works
-if it doesn’t exist
-add a CITE row for the author
-add the newly created CITE id for the author to the MADS file
-generate the CITE id (increments from last id in the table)
-move the MADS file to catalog_data

Does that answer your question, I think it answers mine! :)

**Comment by cwulfman** [comment]
Oy...

This tells me what I need to know, though. If all goes well, I should be able to do this today.

**Comment by AlisonBabeu** [comment]
May the GitHub force be with you!

**Comment by AlisonBabeu** [comment]
I'm closing this issue since this process is no longer relevant.
