### ISSUE TITLE
bulk process all MADS in catalog_pending

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_pending#15]
Following the algorithm here:
https://docs.google.com/document/d/1Oxwg7i0xoo-ym_LfBC3UpsODoCt7z8lQiMlk7szHBiU

For each:
1. Verify the record for XML validity
1. Clean it up (remove stray spaces, empty elements, unnecessary namespaces)
1. Check for duplicates
1. Generate new id
1. Add id to MADS record
1. Create cite element for "cite table"

What could go wrong?

**Comment by AlisonBabeu** [comment]
In my experience @cwulfman and I'm sure in yours it is often better not to ask what could go wrong....just saying!

**Comment by cwulfman** [comment]
The first thing to go wrong: a non-conformant MADS record that threw off the id generator. It's all part of the fun, really!

**Comment by AlisonBabeu** [comment]
Which record I must now, non-conformant records shall perish!

**Comment by cwulfman** [comment]
There were a couple of stray close-brackets in Philocrates/viaf66856353.mads.xml; I fixed 'em.

**Comment by cwulfman** [comment]
@AlisonBabeu  Here's a set of CITE data, extracted from the pending MADS. If you have a chance to glance over them, that would be great; I'll keep massaging the MADS records themselves, too.

[cite-authors-pending.xml.zip](https://github.com/PerseusDL/catalog_pending/files/1613183/cite-authors-pending.xml.zip)

**Comment by AlisonBabeu** [comment]
Hi @cwulfman, I've started to look through this list and it looks pretty accurate so far. One quick question, I've noticed that there appear to be 363 authors, but only 319 `<canonical-id>`.  From a little searching, it appears that the majority of authors that have an ID based on a publication textgroup (e.g. fhg, vor, do not contain this element). Is this a remaining feature of legacy code or a deliberate choice because these IDs are not canonical in the sense of having come from a bibliography?

The other case where there seems to have been an error, is that whenever there was an author with a PHI ID,  hence a canonical ID, for some reason, they did not end up with this element, for example, the author Namusa:
```xml
<author>
    <urn>urn:cite:perseus:author.2020.1</urn>
    <authority-name>Namusa, P. Aufidius (active 1st century B.C)</authority-name>
    <related-works>420.1</related-works>
</author>
```
but within the [authority record](https://github.com/PerseusDL/catalog_pending/blob/master/mads/Aufidius%20Namusa/nr95033832.mads.xml) you find 
```xml
<mads:identifier type="phi">420</mads:identifier>
```
Other examples includes Caelius Sabinus, Bucolica Einsidlensia, Cascellius, Carmen De Bello Aegyptiaco, Caesar, L. Julius, Aquilius Gallus, etc.  What should be done in terms of these records?

**Comment by cwulfman** [comment]
This was a deliberate -- and now, obviously, misguided -- choice on my part: I selected a canonical-id from a prioritized list of

1. citeurn
2. tlg
3. stoa
4. stoa author

So ```fhg``` and ```vor``` should be on this list; what else, and with what priority, when a MADS record contains more than one?

**Comment by AlisonBabeu** [comment]
I started to write an answer to this and then realized, of course, like everything with the Perseus Catalog that it is more complicated than it looks originally.  

The citeurn should be prioritized above all else, but in terms of the canonical identifiers it depended on the language of the author in some cases, since, for example,  Cicero, has a TLG, PHI and STOA.  For Greek authors, they typically only had a TLG ID to prioritize.  For Latin authors, it was more complicated but we prioritized the PHI over the STOA. I'm also realizing that STOA and  STOA author should be the same since they are one in the same.   In the case of fhg, vor, ieg, lyg, plg, caf, and other textgroups created from edition abbreviations, they will likely be the only canonical identifier in a record.

**Comment by cwulfman** [comment]
In other words, something like

1. citeurn
2. stoa
3. stoa author
4. tlg
5. phi
6. fhg | vor | ieg | lyg | plg | caf | ...

**Comment by AlisonBabeu** [comment]
Yes, stoa before stoa author, since it should have always been stoa. Sigh. Though in records with both a STOA and a PHI, please preference the PHI (long story....)

**Comment by cwulfman** [comment]
Oy.   This is a nasty heuristic. Bleh. But I'll do it....

**Comment by cwulfman** [comment]
How about these, @AlisonBabeu ?

[cite-authors-pending.xml.zip](https://github.com/PerseusDL/catalog_pending/files/1616909/cite-authors-pending.xml.zip)

**Comment by AlisonBabeu** [comment]
Those look perfect!

**Comment by cwulfman** [comment]
Cool! I'll merge the ids into the MADS records, then, and move them over to the "pending_review" branch of catalog_data.

**Comment by AlisonBabeu** [comment]
I looked through a number of them and they all looked fine to me.

**Comment by cwulfman** [comment]
The authority records for persons in catalog_pending/mads have now been merged into catalog_data/mads, on the pending-review branch. I've also updated citecoll/authors.xml (the xml version of the CITE tables). They have also been loaded into the bare-bones catalog app on the Digital Ocean server: 

http://174.138.78.35:8080/exist/apps/PerseusCatalog/index.html

**Comment by AlisonBabeu** [comment]
This is a legacy issue and the work on it was completed so I am closing it!
