### ISSUE TITLE
New identifier for Muscio/Mustio

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/catalog_pending#55]
Hey there,

Muscio/Mustio is not recorded anywhere in the catalog or the abbreviation google spreadsheet. Would it be possible to create both a work level and a textgroup level identifier ?

Wikipedia: https://en.wikipedia.org/wiki/Muscio
VIAF: https://viaf.org/viaf/79251637/#Mustio.

Work title: Gynaecia [lat] 

Existing Teubner Edition: https://archive.org/details/gynaeciorumvetus00sorauoft/page/4/mode/2up 

I am in the process of publishing a TEI version of an edition done during a PhD Thesis.

**Comment by AlisonBabeu** [comment]
hi @PonteIneptique as much as I have tried to get out of the habit of creating new IDs in the STOA list, I'll do it this one time again because its you! : ) 

Since I had been in the practice of adding them in alphabetically with letters (I know, I know) you can give this author the bright shiny new textgroup ID of stoa0205b, and this work the ID of stoa0205b.stoa001.

**Comment by PonteIneptique** [comment]
Woohooo :D 
Thank you @AlisonBabeu :)

**Comment by PonteIneptique** [comment]
FYI, I updated the identifier of the edition I released: https://github.com/lascivaroma/additional-texts/blob/master/data/stoa0205b/stoa001/stoa0205b.stoa001.bolton-lat1.xml :)
